#generate a code to take input from user and draw on picture
import cv2
image=cv2.imread("image drawing functions\IMG20250815105348.jpg")
print()
print("---------------------------------------------------------------------------")
a=input("what you wants to draw on your picture(line\ rectangle\ circle\ text): ")
if a.lower()=='line':
    print("enter cordinates for point 1: ")
    x1=int(input("x coordinate:"))
    y1=int(input("y coordinate:"))
    print("enter cordinates for point 2: ")
    x2=int(input("x coordinate:"))
    y2=int(input("y coordinate:"))
    pt1=(x1,y1)
    pt2=(x2,y2)
    print("enter color of your line:")
    r=int(input("enter r(0~255):"))
    g=int(input("enter g(0~255):"))
    b=int(input("enter b(0~255):"))
    color=(b,g,r)
    thick=int(input("enter thickness of your line:"))
    new_image=cv2.line(image, pt1, pt2, color, thick)
    cv2.imshow("lined image", new_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    save=input("do you wants to save your picture?(yes/no): ")
    if save.lower()=="yes":
        cv2.imwrite("image drawing functions\output1.jpg", new_image)
    else:
        print("byy(-\/-)")

elif a.lower()=='rectangle':
    print("enter cordinates for point 1: ")
    x1=int(input("x coordinate:"))
    y1=int(input("y coordinate:"))
    print("enter cordinates for point 2: ")
    x2=int(input("x coordinate:"))
    y2=int(input("y coordinate:"))
    pt1=(x1,y1)
    pt2=(x2,y2)
    print("enter color of your rectangle:")
    r=int(input("enter r(0~255):"))
    g=int(input("enter g(0~255):"))
    b=int(input("enter b(0~255):"))
    color=(b,g,r)
    thick=int(input("enter thickness of your rectangle:"))
    new_image=cv2.rectangle(image, pt1, pt2, color, thick)
    cv2.imshow("rectangle image", new_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    save=input("do you wants to save your picture?(yes/no): ")
    if save.lower()=="yes":
        cv2.imwrite("image drawing functions\output2.jpg", new_image)
    else:
        print("byy(-\/-)")

elif a.lower()=='circle':
    print("enter cordinates for center: ")
    x1=int(input("x coordinate:"))
    y1=int(input("y coordinate:"))
    center=(x1,y1)
    radius=int(input("enter radius of your circle:"))
    print("enter color of your circle:")
    r=int(input("enter r(0~255):"))
    g=int(input("enter g(0~255):"))
    b=int(input("enter b(0~255):"))
    color=(b,g,r)
    thick=int(input("enter thickness of your circle:"))
    new_image=cv2.circle(image, center, radius, color, thick)
    cv2.imshow("circle image", new_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    save=input("do you wants to save your picture?(yes/no): ")
    if save.lower()=="yes":
        cv2.imwrite("image drawing functions\output3.jpg", new_image)
    else:
        print("byy(-\/-)")
elif a.lower()=='text':
    print("enter cordinates for origin: ")
    x1=int(input("x coordinate:"))
    y1=int(input("y coordinate:"))
    origin=(x1,y1)
    text=(input("enter text you wants to display on your picture:"))
    print("enter color of your text:")
    r=int(input("enter r(0~255):"))
    g=int(input("enter g(0~255):"))
    b=int(input("enter b(0~255):"))
    color=(b,g,r)
    thick=int(input("enter thickness of your text:"))
    fontScale=float(input("enter font scale:"))
    new_image=cv2.putText(image, text, origin, cv2.FONT_HERSHEY_COMPLEX, fontScale, color, thick)
    cv2.imshow("text image", new_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    save=input("do you wants to save your picture?(yes/no): ")
    if save.lower()=="yes":
        cv2.imwrite("image drawing functions\output4.jpg", new_image)
    else:
        print("byy(-\/-)")
else:
    print("please choose correctly-----------")
